### PR TITLE
Wordpress XML Import

### PR DESCRIPTION
**Pull request by jgulledge19**
This is a good starting point as this branch currently imports Posts and Pages from Wordpress XML. It also downloads images/documents and puts them in a selected Media Source from with in the Content field. I have tested only from a Wordpress 4.2.2 export so further testing is needed.

### CODE REVIEW

**Comment by jgulledge19** [comment]
Note import does not build out Parent/Child relationships

**Comment by dubrod** [comment]
I Definetly want to help make this happen. My first import was a success, after i checked this empty box. 

image

maybe a label is missing?

still running WP 4.1 on my local machine

**Comment by dubrod** [comment]
how are you thinking of handling the `template`. i was thinking of an input in the ImportX screen that was formatted to map the name to an ID, like...
```
default:1,sidebar:2
```

then we match the name during the loop to decide template ID. I've got the name scrap working.

```
$wpTemplate = "";
		foreach($post->children('wp',true)->postmeta as $wpm){
			if($wpm->meta_key == "_wp_page_template"){
				$wpTemplate = $this->parseContent((string)$wpm->meta_value);
			}	
				
		}
```

wordpressimport.php - line 189 - just before setting the $data

**Comment by jgulledge19** [comment]
@dubrod I added in your suggestion. Want to test again?

**Comment by dubrod** [comment]
oh awesome you started that part. I actually started doing a look up in the modx table for matching tables. 

```
$wpTemplate = "";
		$mxTplId = "";
		foreach($post->children('wp',true)->postmeta as $wpm){
			if($wpm->meta_key == "_wp_page_template"){
				$wpTemplate = $this->parseContent((string)$wpm->meta_value);
				//this breaks the test ability
				$mxTplId = $this->matchTemplate($wpTemplate);
			}	
				
		}
```

```
public function matchTemplate($wpTemplate) {
        $tpl = $this->modx->getObject('modTemplate',array('templatename' => $wpTemplate));
        if ($tpl) {
	        $this->modx->importx->log('template', 'tpl id:' . $tpl->get('id'));
            return $tpl->get('id');
        } else {
	        $this->modx->importx->log('template', 'tpl id: using default');
	        return $this->config['template'];
        }
    }
```

image

email wayne@modx.com we should knock this sucker out!

**Comment by dubrod** [comment]
also @jgulledge19 I am NOT a PHP developer so if I do something you see wrong please change it. =] 

I know enough to be dangerous.

**Comment by jgulledge19** [comment]
Cleaning up my PRs as this is super old.

**Pull request closed without merging**
